name: Развертывание на VPS

on:
  push:
    branches:
      - build

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Проверка кода
      uses: actions/checkout@v2
      
    - name: Настройка Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Установка зависимостей
      run: npm ci
      
    - name: Сборка проекта
      run: npm run build
      
    - name: Развертывание на VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/push-tester
          git pull origin main
          npm ci
          npm run build
          npm run pm2:stop || true
          npm run pm2:delete || true
          npm run pm2:start