name: Развертывание на VPS

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Проверка кода
      uses: actions/checkout@v2
      
    - name: Настройка Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        
    - name: Кэширование зависимостей npm
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.OS }}-node-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.OS }}-node-
        
    - name: Установка зависимостей
      run: npm install
      
    - name: Кэширование сборки
      uses: actions/cache@v2
      with:
        path: |
          ~/.npm
          ${{ github.workspace }}/build
        key: ${{ runner.os }}-react-build-${{ hashFiles('**/package.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          ${{ runner.os }}-react-build-${{ hashFiles('**/package.json') }}-
      
    - name: Сборка проекта
      run: npm run build
      
    - name: Развертывание на VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/push-tester
          git pull origin build
          npm ci
          npm run build
          npm run pm2:stop || true
          npm run pm2:delete || true
          npm run pm2:start
